services:
  - type: web
    name: crm-invoice-manager
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: crm-invoice-db
          property: connectionString
      - key: EMAIL_HOST_USER
        value: "danielbedoyatests@gmail.com"
      - key: EMAIL_PASS
        sync: false
databases:
  - name: crm-invoice-db
    region: oregon
    plan: free