# Generated by Django 4.2.20 on 2025-05-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='period_key',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Periodo de facturación'),
        ),
    ]
