# Generated by Django 4.2.20 on 2025-05-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='status',
        ),
        migrations.AddField(
            model_name='contract',
            name='active',
            field=models.BooleanField(default=True, verbose_name='¿Está activo?'),
        ),
        migrations.AddField(
            model_name='contract',
            name='billing_cycle',
            field=models.CharField(choices=[('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], default='weekly', max_length=10, verbose_name='Ciclo de facturación'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='weekly_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de cada cuota'),
        ),
    ]
