# Generated by Django 4.2.20 on 2025-05-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_remove_contract_status_contract_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor total del contrato'),
        ),
    ]
