# Generated by Django 4.2.20 on 2025-05-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor restante'),
        ),
    ]
