# Generated by Django 4.2.20 on 2025-05-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_fieldpermission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fieldpermission',
            unique_together={('group', 'content_type')},
        ),
        migrations.AddField(
            model_name='fieldpermission',
            name='allowed_fields',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.RemoveField(
            model_name='fieldpermission',
            name='field_name',
        ),
    ]
