# Generated by Django 4.2.20 on 2025-05-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
            ],
        ),
    ]
